services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44049:44049"
    command: make run
    restart: always
    depends_on:
      - db
      - redis
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.prod.yaml:/etc/prometheus/prometheus.prod.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin


volumes:
  app:
  grafana_data: