services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44044:44044"
    command: make run
    restart: always
    depends_on:
      - db
      - redis
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6378:6378"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning


volumes:
  app:
  db:
  redis: