services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44049:44049"
    command: make run
    restart: always
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
volumes:
  app:
  redis: