env: "development"


database:
  host: localhost
  port: "5436"
  user: "postgres"
  dbname: "auth-db"
  max_attempts: 10

prometheus:
  host: "localhost"
  port: 8081
  timeout: 4s
  debug: true
  idle_timeout: 60s

redis:
  host: "localhost"
  port: "6378"
  dbnumber: 0

grpc:
  port: "44049"
  timeout: 360s